### ISSUE TITLE
Composer compatibility

### ISSUE THREAD

**Issue by cosmicdreams** [itsjavi/fontawesome-iconpicker#39]
I would love to use this for a project and would love to be able to use Composer to handle the dependencies.  Ok to contribute a PR that includes proper attribution and Composer support?

**Comment by geerlingguy** [comment]
+1 to this. Font Awesome itself [includes a composer.json](https://github.com/FortAwesome/Font-Awesome/blob/master/composer.json) and is [available on packagist](https://packagist.org/packages/fortawesome/font-awesome).

I'd like to be able to use Font Awesome Iconpicker with a Drupal site using the [Font Awesome Iconpicker](https://www.drupal.org/project/fontawesome_iconpicker) module, but it's difficult to download this library as a dependency on a PHP project the correct way since it's not in Packagist currently.

**Comment by cosmicdreams** [comment]
I've made a PR for this: https://github.com/itsjavi/fontawesome-iconpicker/pull/40

**Comment by itsjavi** [comment]
Resolved. It is released together in v 1.3.0 
https://github.com/itsjavi/fontawesome-iconpicker/releases/tag/1.3.0

Nice to see it is used in Drupal :)

**Comment by geerlingguy** [comment]
@itsjavi - Awesome, thanks!
